-- create table for TEST_PROGRAM_VER_REFERENCE (CE-2628)

CREATE TABLE "REFDB"."TEST_PROGRAM_VER_REFERENCE"
(	"PROGRAM_NAME" VARCHAR2(32 BYTE) NOT NULL,
     "PARAMETERS_HASH" VARCHAR2(100 BYTE) NOT NULL,
     "PROGRAM_VERSION" NUMBER NOT NULL,
     "INSERT_TIME" DATE DEFAULT sysdate,
     "ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY

) TABLESPACE "DP_DATA" ;
GRANT SELECT ON "REFDB"."TEST_PROGRAM_VER_REFERENCE" to PUBLIC;
