INSERT INTO ERT_CONF (CONF_NAME, VALUE_STRING, VALUE_NUMBER, VALUE_BOOLEAN, DATA_TYPE) VALUES ('WS_LOTG_URL', 'http://usco09ls210.onsemi.com:60030/LotGWS/resources/lotg/lot/{lot}/sourceLot', null, 'N', 'STRING');
INSERT INTO ERT_CONF (CONF_NAME, VALUE_STRING, VALUE_NUMBER, VALUE_BOOLEAN, DATA_TYPE) VALUES ('WS_LTM_URL', '', null, 'N', 'STRING');
INSERT INTO ERT_CONF (CONF_NAME, VALUE_STRING, VALUE_NUMBER, VALUE_BOOLEAN, DATA_TYPE) VALUES ('WS_WMC_URL', '', null, 'N', 'STRING');
INSERT INTO ERT_CONF (CONF_NAME, VALUE_STRING, VALUE_NUMBER, VALUE_BOOLEAN, DATA_TYPE) VALUES ('WS_WMC_ID_URL', 'http://grvserv106.usgr1.onsemi.com:8881/wmap-config/resources/reticles/id/{id}', null, 'N', 'STRING');
INSERT INTO ERT_CONF (CONF_NAME, VALUE_STRING, VALUE_NUMBER, VALUE_BOOLEAN, DATA_TYPE) VALUES ('WS_MATCHUP_SCRIBE_URL', 'http://grvserv106.usgr1.onsemi.com:8881/wmap-config/resources/matchup/laserscribe/{lot}/{scribe}/{probeEnd}', null, 'N', 'STRING');
INSERT INTO ERT_CONF (CONF_NAME, VALUE_STRING, VALUE_NUMBER, VALUE_BOOLEAN, DATA_TYPE) VALUES ('WS_MAP_REPOSITORY_URL', '', null, 'N', 'STRING');
INSERT INTO ERT_CONF (CONF_NAME, VALUE_STRING, VALUE_NUMBER, VALUE_BOOLEAN, DATA_TYPE) VALUES ('WS_SCRIBE_TO_VID_URL', 'http://lotg.onsemi.com:60034/WaferScribeWS/resources/waferscribeWS/waferscribe/{scribe}/waferDetails', null, 'N', 'STRING');
INSERT INTO ERT_CONF (CONF_NAME, VALUE_STRING, VALUE_NUMBER, VALUE_BOOLEAN, DATA_TYPE) VALUES ('WS_VID_TO_SCRIBE_URL', 'http://lotg.onsemi.com:60034/WaferScribeWS/resources/waferscribeWS/lot/{lot}/waferDetails', null, 'N', 'STRING');
